import { useMemo } from 'react';
import { useParams } from 'react-router-dom';
import { Card } from '../components/Card.jsx';
import { Badge } from '../components/Badge.jsx';
import { Button } from '../components/Button.jsx';
import { formatKesFromCents } from '../lib/money.js';
import { feeSummary } from '../mock/db.js';

export function ReceiptPage() {
  const { admissionNumber } = useParams();
  const admission_number = decodeURIComponent(admissionNumber || '');

  const summary = useMemo(() => feeSummary(admission_number), [admission_number]);

  if (!summary) {
    return (
      <Card title="Receipt" subtitle="Admission not found">
        <div style={{ fontSize: 13, color: '#6b7280' }}>
          No admission found for <code>{admission_number}</code>.
        </div>
      </Card>
    );
  }

  return (
    <div className="receipt-page">
      <div className="receipt-toolbar no-print">
        <Button
          variant="ghost"
          size="sm"
          onClick={() => window.print()}
        >
          Print / Save as PDF
        </Button>
      </div>

      <div className="receipt-sheet">
        <header className="receipt-header">
          <div className="receipt-brand">
            <div className="receipt-brand-name">Student Fee Tracker</div>
            <div className="receipt-brand-subtitle">
              Official fee clearance receipt
            </div>
          </div>
          <div className="receipt-badge">
            <Badge>{summary.status}</Badge>
          </div>
        </header>

        <section className="receipt-section">
          <div className="receipt-grid-2">
            <div>
              <h3>Student</h3>
              <p className="receipt-strong">{summary.full_name}</p>
              <p>{summary.phone || 'No phone on record'}</p>
            </div>
            <div>
              <h3>Admission</h3>
              <p className="receipt-strong">{summary.admission_number}</p>
              <p>
                Course: {summary.course_name}
                <br />
                Enrolled:{' '}
                {summary.enrolled_at
                  ? new Date(summary.enrolled_at).toLocaleDateString()
                  : '—'}
              </p>
            </div>
          </div>
        </section>

        <section className="receipt-section">
          <h3>Fee summary</h3>
          <div className="receipt-grid-3">
            <Metric label="Total fee" value={formatKesFromCents(summary.total_fee)} />
            <Metric label="Total paid" value={formatKesFromCents(summary.total_paid)} />
            <Metric label="Balance" value={formatKesFromCents(summary.balance)} />
          </div>
        </section>

        <section className="receipt-section">
          <h3>Payments</h3>
          {summary.payments.length === 0 ? (
            <p className="receipt-muted">No payments recorded.</p>
          ) : (
            <table className="receipt-table">
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Amount</th>
                  <th>Receipt</th>
                  <th>Payer</th>
                  <th>Account reference</th>
                </tr>
              </thead>
              <tbody>
                {summary.payments.map((p) => (
                  <tr key={p.payment_id}>
                    <td>
                      {p.transaction_time
                        ? new Date(p.transaction_time).toLocaleString()
                        : '—'}
                    </td>
                    <td className="receipt-table-number">
                      {formatKesFromCents(p.amount)}
                    </td>
                    <td>{p.mpesa_receipt}</td>
                    <td>{p.payer_name || p.payer_phone || '—'}</td>
                    <td>{p.admission_number}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </section>

        <section className="receipt-section">
          <h3>Message</h3>
          <p className="receipt-message">
            This receipt confirms the fee position for the above student as of{' '}
            {new Date().toLocaleString()}. Please keep this document for your
            records. For any discrepancies, contact the finance office with this
            admission number and M-Pesa receipt references.
          </p>
        </section>

        <footer className="receipt-footer">
          <p>Generated by Student Fee Tracker</p>
        </footer>
      </div>
    </div>
  );
}

function Metric({ label, value }) {
  return (
    <div className="receipt-metric">
      <div className="receipt-metric-label">{label}</div>
      <div className="receipt-metric-value">{value}</div>
    </div>
  );
}

